### ISSUE TITLE
ModuleNotFoundError: No module named 'models'

### ISSUE THREAD

**Issue by lip111** [bubbliiiing/yolox-pytorch#116]
D:\Anaconda\envs\pytorch-gpu\python.exe O:\graduate\yolov7-bubbliiiing\predict.py 
Traceback (most recent call last):
  File "O:\graduate\yolov7-bubbliiiing\predict.py", line 15, in <module>
    yolo = YOLO()
  File "O:\graduate\yolov7-bubbliiiing\yolo.py", line 95, in __init__
    self.generate()
  File "O:\graduate\yolov7-bubbliiiing\yolo.py", line 108, in generate
    self.net.load_state_dict(torch.load(self.model_path, map_location=device))
  File "D:\Anaconda\envs\pytorch-gpu\lib\site-packages\torch\serialization.py", line 592, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "D:\Anaconda\envs\pytorch-gpu\lib\site-packages\torch\serialization.py", line 851, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'models'

我将从别的地方得到的 XXX.pt 放logs文件夹，然后修改了yolo.py中的model_path,接着运行就报这个错误了

**Comment by lip111** [comment]
我把权值文件弄错了，下载了个.pt的，换成.pth的就可以检测了😂
