### ISSUE TITLE
仅含有Backbone的预训练权重

### ISSUE THREAD

**Issue by YoungLNB** [bubbliiiing/yolox-pytorch#56]
我看您提供的都是整个网络训练好的权重，有没有只有backbone(cspdarknet53)的权重呢

**Comment by bubbliiiing** [comment]
YoloX官方说，得益于mosaic强大的数据增强能力，不需要主干的预训练，你可以重新git一下，我写了注释

**Comment by YoungLNB** [comment]
直接加载在coco训练好的模型，然后再训练voc数据集，得到的mAP有87.84，我觉得有点高，但是不加载预训练模型，mAP又很低，所以我想的是只让加载backbone的部分权重进行训练

**Comment by bubbliiiing** [comment]
没有的，你直接从0开始应该是80多一点点好像

**Comment by illrayy** [comment]
train.py line201
`pretrained_dict = {k: v for k, v in pretrained_dict.items() if np.shape(model_dict[k]) == np.shape(v)}`
改成
`pretrained_dict = {k: v for k, v in pretrained_dict.items() if np.shape(model_dict[k]) == np.shape(v) and 'backbone.backbone' in k}`

**Comment by bubbliiiing** [comment]
这样加载预训练也是coco的

**Comment by illrayy** [comment]
> 这样加载预训练也是coco的

但他的要求是主干网络加载预训练权重啊，没说是coco的预训练权重还是imagenet的预训练权重。而且就yolox来说用coco的效果应该更好吧，用imagenet预训练确实会掉点，还特别慢

**Comment by illrayy** [comment]
可能是我用的imagenet 1k，没用21k，iter也不够，在另一个数据集上的效果是不如coco预训练的。但我用1k都有点炼不动，太大了

**Comment by 2024zky** [comment]
self.backbone       = CSPDarknet(depth, width, depthwise = depthwise, act = act)
大佬，您把主干网络的读取放在PAFPN中，因为我要更换PAFPN，所以就把主干网络的提取放在YoloBody中,如下：
self.backbone1 =   CSPDarknet(depth, width, depthwise = depthwise, act =  "silu")
self.in_features = ("dark3", "dark4", "dark5")
self.neck   = YOLOPAFPN(depth, width, depthwise=depthwise)
然后就报错:
 File "train.py", line 140, in <module>
    pretrained_dict = {k: v for k, v in pretrained_dict.items() if np.shape(model_dict[k]) == np.shape(v)}
  File "train.py", line 140, in <dictcomp>
    pretrained_dict = {k: v for k, v in pretrained_dict.items() if np.shape(model_dict[k]) == np.shape(v)}
KeyError: 'backbone.backbone.stem.conv.conv.weight'
为什么会报错？不是说不改变主干刚网络就不会报错吗？

**Comment by bubbliiiing** [comment]
你这个是train.py报的错

**Comment by 2024zky** [comment]
改了之后不输入权重不报错，
不改故意输入版本不对的权重
nitialize network with normal type
Load weights model_data/yolox_x.pth.
Traceback (most recent call last):
  File "F:/yoloX_ASFF/yolox-pytorch-main/train.py", line 140, in <module>
    pretrained_dict = {k: v for k, v in pretrained_dict.items() if np.shape(model_dict[k]) == np.shape(v)}
  File "F:/yoloX_ASFF/yolox-pytorch-main/train.py", line 140, in <dictcomp>
    pretrained_dict = {k: v for k, v in pretrained_dict.items() if np.shape(model_dict[k]) == np.shape(v)}
KeyError: 'backbone.backbone.dark2.1.m.1.conv1.conv.weight'

这样做对比难道还不是权重有问题报错吗？

**Comment by bubbliiiing** [comment]
有个问题汇总你看一下吧，里面有说怎么比较shape然后加载权重

**Comment by lunaWU628** [comment]
> YoloX官方说，得益于mosaic强大的数据增强能力，不需要主干的预训练，你可以重新git一下，我写了注释

意思就是说，替换了backbone后，用原来的预训练模型也是可以的嘛？（试了一下，不改预训练模型的情况下，替换掉backbone后也是可以用的，但精度下降了，我换了两个backbone，精度都不如YOLOX的backbone，是没有改预训练模型的原因嘛？）
