### ISSUE TITLE
 fit_one_epoch 函数的问题

### ISSUE THREAD

**Issue by jiangxiaogg** [bubbliiiing/yolox-pytorch#70]
我用的yolox-nano模型，加载的权重也是B导提供的，在COLAB上跑的。
在训练的时候报错 TypeError: 'bool' object is not callable
查了下说是某些变量身兼数值的原因。
希望B导能够解释解释

**Comment by jiangxiaogg** [comment]
数职

**Comment by jiangxiaogg** [comment]
还有一个问题是同时报错的
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "<ipython-input-11-8a12fae1ebec>", line 40, in __getitem__
    shuffle(lines)

**Comment by bubbliiiing** [comment]
是否因为图片太少？

**Comment by jiangxiaogg** [comment]
> 

我今天怀疑是我自己制作的数据集标签啊什么的对不上，所以用了B导提供的VOC那个2W+的数据集，然后裁剪了下，选了前2400张图片和相应的标签文件添加到colab进行训练，同样出现了这个问题，就是**TypeError: Caught TypeError in DataLoader worker process 0.**+**TypeError: 'range' object is not callable**。我再试试添加数据，把20000多张图片全部添加。我自己标注的数据集才450多张，后面添加的才2400张（因为我看B导视频里有一段是是2311张进行训练）。可能是图片太少了，我再试试下，感谢回复，明天出结果再回复你！

**Comment by jiangxiaogg** [comment]
解决了，老哥。
我去翻需求txt,发现需要的Pillow==8.2.0，在colab上只有Pillow == 7.1.2，pip install之后就解决了

**Comment by bubbliiiing** [comment]
0 0竟然可以这样
