### ISSUE TITLE
nano training error: RuntimeError: stack expects each tensor to be equal size, but got [1] at entry 0 and [] at entry 1

### ISSUE THREAD

**Issue by xiaoloudexiaofang** [bubbliiiing/yolox-pytorch#80]
##up主你好，我最近遇到一个问题，想求教一下：
#####问题描述：yolo_nano训练时会报错，但是s、m、l、x和tiny模型不会报错。
#####问题补充：对batch进行了测试，当batch=1时，不会报错，当batch>=2时，会报错。
#####报错结果：
2022-05-22 20:33:20 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (8120), thread 'MainThread' (15452):
Traceback (most recent call last):

  File "E:/works/study/yolox\train.py", line 135, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=4, cache=False, ckpt='./weights/yolox_nano.pth', devices=1, dist_backend='nccl', dist_url=None, exp_file...
          └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "E:\works\study\yolox\yolox\core\launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x0000023BABF89828>

  File "E:/works/study/yolox\train.py", line 113, in main
    trainer.train()
    │       └ <function Trainer.train at 0x0000023BB38D5EE8>
    └ <yolox.core.trainer.Trainer object at 0x0000023BB6AD53C8>

  File "E:\works\study\yolox\yolox\core\trainer.py", line 70, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x0000023BB6A8D4C8>
    └ <yolox.core.trainer.Trainer object at 0x0000023BB6AD53C8>

  File "E:\works\study\yolox\yolox\core\trainer.py", line 152, in before_train
    self.prefetcher = DataPrefetcher(self.train_loader)
    │                 │              │    └ <yolox.data.dataloading.DataLoader object at 0x0000023B83E32C08>
    │                 │              └ <yolox.core.trainer.Trainer object at 0x0000023BB6AD53C8>
    │                 └ <class 'yolox.data.data_prefetcher.DataPrefetcher'>
    └ <yolox.core.trainer.Trainer object at 0x0000023BB6AD53C8>

  File "E:\works\study\yolox\yolox\data\data_prefetcher.py", line 21, in __init__
    self.preload()
    │    └ <function DataPrefetcher.preload at 0x0000023BB4356558>
    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x0000023BB4B53D88>

  File "E:\works\study\yolox\yolox\data\data_prefetcher.py", line 25, in preload
    self.next_input, self.next_target, _, _ = next(self.loader)
    │                │                             │    └ <torch.utils.data.dataloader._SingleProcessDataLoaderIter object at 0x0000023BBDFDB048>
    │                │                             └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x0000023BB4B53D88>
    │                └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x0000023BB4B53D88>
    └ <yolox.data.data_prefetcher.DataPrefetcher object at 0x0000023BB4B53D88>

  File "C:\Anaconda3\envs\yolox\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
           │    └ <function _SingleProcessDataLoaderIter._next_data at 0x0000023BB2C8B5E8>
           └ <torch.utils.data.dataloader._SingleProcessDataLoaderIter object at 0x0000023BBDFDB048>

  File "C:\Anaconda3\envs\yolox\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           │    │                │     └ [(True, tensor(122)), (True, tensor(388)), (True, tensor(419)), (True, tensor(663))]
           │    │                └ <function _MapDatasetFetcher.fetch at 0x0000023BB2C84C18>
           │    └ <torch.utils.data._utils.fetch._MapDatasetFetcher object at 0x0000023B83E1B548>
           └ <torch.utils.data.dataloader._SingleProcessDataLoaderIter object at 0x0000023BBDFDB048>

  File "C:\Anaconda3\envs\yolox\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
           │    │          └ [(array([[[ 50.,  54.,  56., ...,  40.,  40.,  42.],
           │    │                    [ 51.,  54.,  54., ...,  38.,  42.,  47.],
           │    │                    [ 50.,  52., ...
           │    └ <function default_collate at 0x0000023BB2C84288>
           └ <torch.utils.data._utils.fetch._MapDatasetFetcher object at 0x0000023B83E1B548>

  File "C:\Anaconda3\envs\yolox\lib\site-packages\torch\utils\data\_utils\collate.py", line 87, in default_collate
    return [default_collate(samples) for samples in transposed]
            │                                       └ <zip object at 0x0000023B83E1B248>
            └ <function default_collate at 0x0000023BB2C84288>

  File "C:\Anaconda3\envs\yolox\lib\site-packages\torch\utils\data\_utils\collate.py", line 87, in <listcomp>
    return [default_collate(samples) for samples in transposed]
            │               │            └ (array([122], dtype=int64), tensor(388), array([419], dtype=int64), tensor(663))
            │               └ (array([122], dtype=int64), tensor(388), array([419], dtype=int64), tensor(663))
            └ <function default_collate at 0x0000023BB2C84288>

  File "C:\Anaconda3\envs\yolox\lib\site-packages\torch\utils\data\_utils\collate.py", line 67, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
           │                │     │                     └ (array([122], dtype=int64), tensor(388), array([419], dtype=int64), tensor(663))
           │                │     └ <built-in method as_tensor of type object at 0x00007FFB7D9B35E0>
           │                └ <module 'torch' from 'C:\\Anaconda3\\envs\\yolox\\lib\\site-packages\\torch\\__init__.py'>
           └ <function default_collate at 0x0000023BB2C84288>

  File "C:\Anaconda3\envs\yolox\lib\site-packages\torch\utils\data\_utils\collate.py", line 59, in default_collate
    return torch.stack(batch, 0, out=out)
           │     │     │             └ None
           │     │     └ [tensor([122]), tensor(388), tensor([419]), tensor(663)]
           │     └ <built-in method stack of type object at 0x00007FFB7D9B35E0>
           └ <module 'torch' from 'C:\\Anaconda3\\envs\\yolox\\lib\\site-packages\\torch\\__init__.py'>

有时候是：RuntimeError: stack expects each tensor to be equal size, but got [1] at entry 0 and [] at entry 1
或者是：TypeError: expected Tensor as element 2 in argument 0, but got numpy.ndarray
求大神帮解决。

**Comment by bubbliiiing** [comment]
这是官方库的问题

**Comment by xiaoloudexiaofang** [comment]
感谢您及时回复，您那边有没有好一些的解决方案？换个torch版本什么的

**Comment by bubbliiiing** [comment]
我印象中只要照着官方步骤走，一点问题都没有
![image](https://user-images.githubusercontent.com/47347516/169696557-79e232e4-cc30-40bc-b695-d30804cc6a5f.png)

**Comment by xiaoloudexiaofang** [comment]
好的，我再尝试一下，非常感谢您热心回复。

**Comment by WangRuixin93** [comment]
你好，我也在训nano，我目前虽然没遇到你的问题，但出现报错：C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Loss.cu:115: block: [0,0,0], thread: [15,0,0] Assertion `input_val >= zero && input_val <= one` failed
RuntimeError: CUDA error: device-side assert triggered
请问你有遇到过吗

**Comment by bubbliiiing** [comment]
种类名字写错了？

**Comment by bubbliiiing** [comment]
按照你提的issue描述，应该是你的显卡被别的东西占用了
