### ISSUE TITLE
训练nano版本，25 epoch时报错RuntimeError: CUDA error: device-side assert triggered咋回事呢

### ISSUE THREAD

**Issue by WangRuixin93** [bubbliiiing/yolox-pytorch#95]
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Loss.cu:102: block: [4,0,0], thread: [28,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Loss.cu:102: block: [4,0,0], thread: [29,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Loss.cu:102: block: [4,0,0], thread: [30,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/Loss.cu:102: block: [4,0,0], thread: [31,0,0] Assertion `input_val >= zero && input_val <= one` failed.
Traceback (most recent call last):
  File "D:/Eneedle/algorithm/optical_flow/yolox-pytorch-main/train.py", line 515, in <module>
    fit_one_epoch(model_train, model, ema, yolo_loss, loss_history, eval_callback, optimizer, epoch, epoch_step, epoch_step_val, gen, gen_val, UnFreeze_Epoch, Cuda, fp16, scaler, save_period, save_dir, local_rank)
  File "D:\Eneedle\algorithm\optical_flow\yolox-pytorch-main\utils\utils_fit.py", line 53, in fit_one_epoch
    loss_value = yolo_loss(outputs, targets)
  File "D:\anaconda\envs\tf\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Eneedle\algorithm\optical_flow\yolox-pytorch-main\nets\yolo_training.py", line 94, in forward
    return self.get_losses(x_shifts, y_shifts, expanded_strides, labels, torch.cat(outputs, 1))
  File "D:\Eneedle\algorithm\optical_flow\yolox-pytorch-main\nets\yolo_training.py", line 171, in get_losses
    expanded_strides, x_shifts, y_shifts, 
  File "D:\anaconda\envs\tf\lib\site-packages\torch\autograd\grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "D:\Eneedle\algorithm\optical_flow\yolox-pytorch-main\nets\yolo_training.py", line 240, in get_assignments
    num_fg, gt_matched_classes, pred_ious_this_matching, matched_gt_inds = self.dynamic_k_matching(cost, pair_wise_ious, gt_classes, num_gt, fg_mask)
  File "D:\Eneedle\algorithm\optical_flow\yolox-pytorch-main\nets\yolo_training.py", line 357, in dynamic_k_matching
    _, pos_idx = torch.topk(cost[gt_idx], k=dynamic_ks[gt_idx].item(), largest=False)
RuntimeError: CUDA error: device-side assert triggered
Epoch 25/400:  64%|██████▎   | 7/11 [00:59<00:34,  8.52s/it, loss=8.2, lr=0.0347]

**Comment by bubbliiiing** [comment]
如果前面epoch没错，就是显卡被占用了

**Comment by WangRuixin93** [comment]
有可能，做了两件事，关了fp16，减小了batchsize后没出现，具体是哪个起作用不太清楚

**Comment by neuhsm** [comment]
https://github.com/bubbliiiing/yolox-pytorch/issues/121#issuecomment-1451785512  参考这个？
